### ISSUE TITLE
bspwm displaying default settings

### ISSUE THREAD

**Issue by hzr4zdw2** [RishitPandey/bspwm-config#1]
I installed bspwm and sxhkd on a clean Arch Linux system (brand new installation), then followed the steps provided by this guide to get this theme (I installed feh, picom, rofi, imagemagick, wal and polybar, then copied the config folders and the picom config file into .config). I rebooted and then logged in, but bspwm appeared as a default install (black background, no bars, only cursor is showing). 

I tried installing alacritty and then launching it with super+Return (as was stated in sxhkdrc), but it didn't work. Then I installed another terminal program (termite), replaced it in sxhkdrc as the default terminal application, and tried to launch it with super+Return, but it also didn't work. super+d also doesn't seem to trigger rofi (which is odd, because I had made sure I had rofi installed).

Maybe I am missing a step? It's my first time trying bspwm. Thanks in advance.

**Comment by rishitxyz** [comment]
Ahh...Okay so, what I will recommend is remove all of the files that you copied from my repository and try using the example configs for bspwm and sxhkd available in `/usr/share/doc/bspwm/examples` and copy then into the respective directories and then edit them accordingly. Then if it works copy the configuration lines in my files.

Also check this post I hope it will solve some of your problems: [reddit post](https://www.reddit.com/r/archlinux/comments/2tzvn1/bspwm_not_launching/)

**Comment by hzr4zdw2** [comment]
That seemed to do the trick, much appreciated.

Thank you!

**Comment by rishitxyz** [comment]
I am happy that it worked for you.

Thank you for trying my bspwm setup!
